export function parseArgs(argv) {
  const [command = 'help', ...rest] = argv;
  const options = { paths: [] };

  for (let index = 0; index < rest.length; index += 1) {
    const value = rest[index];
    if (value === '--json') options.json = true;
    else if (value === '--quick') options.quick = true;
    else if (value === '--dry-run') options.dryRun = true;
    else if (value === '--no-integrations') options.integrations = false;
    else if (value === '--no-color') options.color = false;
    else if (value === '--provider') options.provider = rest[++index];
    else if (value.startsWith('--provider=')) options.provider = value.slice(11);
    else if (value === '--compare') options.compare = true;
    else if (value === '--compact-budget') options.compactBudget = Number(rest[++index]);
    else if (value.startsWith('--compact-budget=')) options.compactBudget = Number(value.slice(17));
    else if (value === '--eviction-policy') options.evictionPolicy = rest[++index];
    else if (value.startsWith('--eviction-policy=')) options.evictionPolicy = value.slice(18);
    else if (value === '--summary-top') options.summaryTop = Number(rest[++index]);
    else if (value.startsWith('--summary-top=')) options.summaryTop = Number(value.slice(14));
    else if (value === '--dataset') options.dataset = rest[++index];
    else if (value.startsWith('--dataset=')) options.dataset = value.slice(10);
    else if (value === '--split') options.split = rest[++index];
    else if (value.startsWith('--split=')) options.split = value.slice(8);
    else if (value === '--model') options.model = rest[++index];
    else if (value.startsWith('--model=')) options.model = value.slice(8);
    else if (value === '--llm') options.llm = rest[++index];
    else if (value.startsWith('--llm=')) options.llm = value.slice(6);
    else if (value === '--router') options.router = rest[++index];
    else if (value.startsWith('--router=')) options.router = value.slice(9);
    else if (value === '--router-llm') options.routerLlm = rest[++index];
    else if (value.startsWith('--router-llm=')) options.routerLlm = value.slice(13);
    else if (value === '--embedding-url') options.embeddingUrl = rest[++index];
    else if (value.startsWith('--embedding-url=')) options.embeddingUrl = value.slice(16);
    else if (value === '--embedding-backend') options.embeddingBackend = rest[++index];
    else if (value.startsWith('--embedding-backend=')) options.embeddingBackend = value.slice(20);
    else if (value === '--embedding-model') options.embeddingModel = rest[++index];
    else if (value.startsWith('--embedding-model=')) options.embeddingModel = value.slice(18);
    else if (value === '--strict-router') options.strictRouter = true;
    else if (value === '--no-embeddings') options.embeddings = false;
    else if (value === '--allow-cloud-bodies') options.allowCloudBodies = true;
    else if (value === '--reranker') options.reranker = rest[++index];
    else if (value.startsWith('--reranker=')) options.reranker = value.slice(11);
    else if (value === '--reranker-url') options.rerankerUrl = rest[++index];
    else if (value.startsWith('--reranker-url=')) options.rerankerUrl = value.slice(15);
    else if (value === '--retrieval-k') options.retrievalK = Number(rest[++index]);
    else if (value.startsWith('--retrieval-k=')) options.retrievalK = Number(value.slice(14));
    else if (value === '--reranker-timeout') options.rerankerTimeout = Number(rest[++index]);
    else if (value.startsWith('--reranker-timeout=')) options.rerankerTimeout = Number(value.slice(19));
    else if (value === '--rerank-threshold') options.rerankThreshold = Number(rest[++index]);
    else if (value.startsWith('--rerank-threshold=')) options.rerankThreshold = Number(value.slice(19));
    else if (value === '--chunk-chars') options.chunkChars = Number(rest[++index]);
    else if (value.startsWith('--chunk-chars=')) options.chunkChars = Number(value.slice(14));
    else if (value === '--chunk-overlap') options.chunkOverlap = Number(rest[++index]);
    else if (value.startsWith('--chunk-overlap=')) options.chunkOverlap = Number(value.slice(16));
    else if (value === '--embedding-batch-size') options.embeddingBatchSize = Number(rest[++index]);
    else if (value.startsWith('--embedding-batch-size=')) options.embeddingBatchSize = Number(value.slice(23));
    else if (value === '--checkpoint-every') options.checkpointEvery = Number(rest[++index]);
    else if (value.startsWith('--checkpoint-every=')) options.checkpointEvery = Number(value.slice(19));
    else if (value === '--load-k') options.loadK = Number(rest[++index]);
    else if (value.startsWith('--load-k=')) options.loadK = Number(value.slice(9));
    else if (value === '--sample-tasks') options.sampleTasks = Number(rest[++index]);
    else if (value.startsWith('--sample-tasks=')) options.sampleTasks = Number(value.slice(15));
    else if (value === '--sample-skills') options.sampleSkills = Number(rest[++index]);
    else if (value.startsWith('--sample-skills=')) options.sampleSkills = Number(value.slice(16));
    else if (value === '--sample-seed') options.sampleSeed = rest[++index];
    else if (value.startsWith('--sample-seed=')) options.sampleSeed = value.slice(14);
    else if (value === '--sample-output') options.sampleOutput = rest[++index];
    else if (value.startsWith('--sample-output=')) options.sampleOutput = value.slice(16);
    else if (value === '--eval-cache-dir') options.evalCacheDir = rest[++index];
    else if (value.startsWith('--eval-cache-dir=')) options.evalCacheDir = value.slice(17);
    else if (value === '--lexical-score') options.lexicalScore = Number(rest[++index]);
    else if (value.startsWith('--lexical-score=')) options.lexicalScore = Number(value.slice(16));
    else if (value === '--lexical-margin') options.lexicalMargin = Number(rest[++index]);
    else if (value.startsWith('--lexical-margin=')) options.lexicalMargin = Number(value.slice(17));
    else if (value === '--semantic-threshold') options.semanticThreshold = Number(rest[++index]);
    else if (value.startsWith('--semantic-threshold=')) options.semanticThreshold = Number(value.slice(21));
    else if (value === '--semantic-margin') options.semanticMargin = Number(rest[++index]);
    else if (value.startsWith('--semantic-margin=')) options.semanticMargin = Number(value.slice(18));
    else if (value === '--min-confidence') options.minConfidence = Number(rest[++index]);
    else if (value.startsWith('--min-confidence=')) options.minConfidence = Number(value.slice(17));
    else if (value === '--embedding-timeout') options.embeddingTimeout = Number(rest[++index]);
    else if (value.startsWith('--embedding-timeout=')) options.embeddingTimeout = Number(value.slice(20));
    else if (value === '--min-score') options.minScore = Number(rest[++index]);
    else if (value.startsWith('--min-score=')) options.minScore = Number(value.slice(12));
    else if (value === '--name-weight') options.nameWeight = Number(rest[++index]);
    else if (value.startsWith('--name-weight=')) options.nameWeight = Number(value.slice(14));
    else if (value === '--description-weight') options.descriptionWeight = Number(rest[++index]);
    else if (value.startsWith('--description-weight=')) options.descriptionWeight = Number(value.slice(21));
    else if (value === '--exact-name-weight') options.exactNameWeight = Number(rest[++index]);
    else if (value.startsWith('--exact-name-weight=')) options.exactNameWeight = Number(value.slice(20));
    else if (value === '--top') options.top = Number(rest[++index]);
    else if (value.startsWith('--top=')) options.top = Number(value.slice(6));
    else if (value === '--budget') options.budget = Number(rest[++index]);
    else if (value.startsWith('--budget=')) options.budget = Number(value.slice(9));
    else if (value === '--runs') options.runs = Number(rest[++index]);
    else if (value.startsWith('--runs=')) options.runs = Number(value.slice(7));
    else if (value === '--state-dir') options.stateDir = rest[++index];
    else if (value.startsWith('--state-dir=')) options.stateDir = value.slice(12);
    else if (value === '--tone') options.tone = rest[++index];
    else if (value.startsWith('--tone=')) options.tone = value.slice(7);
    else if (value === '--tier') options.tier = rest[++index];
    else if (value.startsWith('--tier=')) options.tier = value.slice(7);
    else if (value === '--output') options.output = rest[++index];
    else if (value.startsWith('--output=')) options.output = value.slice(9);
    else if (value === '--host') options.host = rest[++index];
    else if (value.startsWith('--host=')) options.host = value.slice(7);
    else if (value === '--port') options.port = Number(rest[++index]);
    else if (value.startsWith('--port=')) options.port = Number(value.slice(7));
    else if (value === '--python') options.python = rest[++index];
    else if (value.startsWith('--python=')) options.python = value.slice(9);
    else if (value === '--hook-timeout') options.hookTimeout = Number(rest[++index]);
    else if (value.startsWith('--hook-timeout=')) options.hookTimeout = Number(value.slice(15));
    else if (value === '--share') {
      const next = rest[index + 1];
      options.share = next && !next.startsWith('-') ? rest[++index] : 'skillram-receipt.svg';
    } else if (value.startsWith('--share=')) options.share = value.slice(8);
    else if (value.startsWith('-')) throw new Error(`Unknown option: ${value}`);
    else options.paths.push(value);
  }

  return { command, options };
}
